#SPDX-License-Identifier: MIT-0
---
# handlers file for postgresql.role
- name: restart postgresql service
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    sleep: 5