#SPDX-License-Identifier: MIT-0
---
# tasks file for postgresql.role
- include_tasks: variables.yml

#Setup /install task
- include_tasks: setup-package.yml
#  when: ansible_distribution == "AlmaLinux"

- include_tasks: initialize.yml

- name: Ensure PostgreSQL is started and enabled
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

- import_tasks: users.yml