---
- name: Include OS-specific variables
  include_vars:
    file: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution in ["AlmaLinux", "Ubuntu", "Alpine"]